server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:${MYSQL_PUBLIC_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          characterEncoding: utf8
          useUnicode: true
  sql:
    init:
      mode: never

# JWT 설정
jwt:
  secret-key: ${JWT_SECRET_KEY}

# Swagger/OpenAPI 설정 (프로덕션에서는 보안상 비활성화 권장)
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# 프로덕션 로깅 설정
logging:
  level:
    root: INFO
    com.kopo_team4.auth_backend: INFO
